site_name: Raspinetes
site_description: Wiki Clúster de Kubernetes en Raspberry Pi
site_author: Tzinm

repo_name: tzinm/raspinetes
repo_url: https://github.com/tzinm/raspinetes

copyright: Copyright &copy; 2020 Tzinm

edit_uri: ''

theme:
  name: material
  language: es
  include_sidebar: true
  palette:
    primary: light blue
    accent: light blue
  font:
    text: PT Sans
    code: PT Sans Mono
  icon:
    logo: octicons/book
    repo: fontawesome/brands/github
  features:
    - tabs: false
    - instant
  favicon: assets/images/favicon.png

markdown_extensions:
  - admonition
  - codehilite:
     linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
      permalink: "#"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.tilde

plugins:
  - search:
      lang:
        - es
#  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/tzinm
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/tzinm
    - icon: fontawesome/brands/telegram
      link: https://t.me/tzinm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tzinm1

nav:
 - Kubernetes: index.md
 - Kubectl: Kubectl.md
 - Kubernetes en RPi: Kubernetes-RaspberryPi.md
 - Referencias: Referencias.md
