apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-blog-nfs
  namespace: ghost-blog
  labels:
    volume: ghost-nfs
spec:
  storageClassName: storage-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.11.220
    path: "/nfs/ghost"
